version: '3.8'

services:
  web:
    build: .
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - web_build:/app/_build
      - ./.env:/app/.env
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
      - ./assets/css:/app/assets/css
      - ./assets/js:/app/assets/js
      - ./assets/static:/app/assets/static
      - ./assets/package.json:/app/assets/package.json
      - ./assets/package-lock.json:/app/assets/package-lock.json
      - ./assets/webpack.config.js:/app/assets/webpack.config.js
      - ./deps:/app/deps
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./test:/app/test

volumes:
  db_data:
  web_build:
